"""initial companies table

Revision ID: 268bcf4d088c
Revises: 
Create Date: 2026-01-30 10:13:43.102515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268bcf4d088c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nombre de la empresa'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='Nombre para mostrar de la empresa'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción de la empresa'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Estado de la empresa (active, inactive, suspended)'),
    sa.Column('tenant_id', sa.String(length=255), nullable=False, comment='ID del tenant para Row Level Security'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de última actualización'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
